import type { Metadata } from "next";
import Footer from "./components/footer";
import Navbar from "./components/navbar";
import ThemeSwitch from "./components/theme-switch";
import { inter } from "./components/ui/fonts";
import ThemeContextProvider from "./context/theme-context";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body
        className={`${inter.className} antialiased bg-slate-50 text-slate-900 dark:bg-slate-900 dark:text-slate-50 dark:text-opacity-90`}
      >
        <ThemeContextProvider>
          <Navbar />
          <main className="mx-auto">{children}</main>
          <ThemeSwitch />
          <Footer />
        </ThemeContextProvider>
      </body>
    </html>
  );
}
